---
- name: apply common utilities setup
  hosts: all
  sudo_user: root
  sudo: yes
  roles:
    - common

- name: apply dev utilities setup
  hosts: dev
  sudo_user: root
  sudo: yes
  roles:
    - dev-installations


