---
- name: apply common utilities setup
  hosts: all
  remote_user: osboxes
  sudo: true
  roles:
    - common

- name: apply dev utilities setup
  hosts: dev
  remote_user: osboxes
  sudo: true
  roles:
    - dev-installations


