---
 - shell: whoami
   register: output
 - debug: var=output.stdout
 - apt: update_cache=yes
 - apt: name={{ item }} state=present
   with_items:
     - iptraf-ng
     - htop
     - mc
     - git
     - openjdk-6-jdk
     - openjdk-8-jdk
     - mysql-client-core-5.6

   register: output
 - debug: var=output.msg


